// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: triple_wrapper.proto

package org.apache.dubbo.triple;

public final class TripleWrapper {
  private TripleWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TripleRequestWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.apache.dubbo.triple.TripleRequestWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * hessian4
     * json
     * </pre>
     *
     * <code>string serializeType = 1;</code>
     * @return The serializeType.
     */
    String getSerializeType();
    /**
     * <pre>
     * hessian4
     * json
     * </pre>
     *
     * <code>string serializeType = 1;</code>
     * @return The bytes for serializeType.
     */
    com.google.protobuf.ByteString
        getSerializeTypeBytes();

    /**
     * <code>repeated bytes args = 2;</code>
     * @return A list containing the args.
     */
    java.util.List<com.google.protobuf.ByteString> getArgsList();
    /**
     * <code>repeated bytes args = 2;</code>
     * @return The count of args.
     */
    int getArgsCount();
    /**
     * <code>repeated bytes args = 2;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    com.google.protobuf.ByteString getArgs(int index);

    /**
     * <code>repeated string argTypes = 3;</code>
     * @return A list containing the argTypes.
     */
    java.util.List<String>
        getArgTypesList();
    /**
     * <code>repeated string argTypes = 3;</code>
     * @return The count of argTypes.
     */
    int getArgTypesCount();
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param index The index of the element to return.
     * @return The argTypes at the given index.
     */
    String getArgTypes(int index);
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the argTypes at the given index.
     */
    com.google.protobuf.ByteString
        getArgTypesBytes(int index);
  }
  /**
   * Protobuf type {@code org.apache.dubbo.triple.TripleRequestWrapper}
   */
  public static final class TripleRequestWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.apache.dubbo.triple.TripleRequestWrapper)
      TripleRequestWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TripleRequestWrapper.newBuilder() to construct.
    private TripleRequestWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TripleRequestWrapper() {
      serializeType_ = "";
      args_ = java.util.Collections.emptyList();
      argTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TripleRequestWrapper();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_org_apache_dubbo_triple_TripleRequestWrapper_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_org_apache_dubbo_triple_TripleRequestWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper.class, org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper.Builder.class);
    }

    public static final int SERIALIZETYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object serializeType_ = "";
    /**
     * <pre>
     * hessian4
     * json
     * </pre>
     *
     * <code>string serializeType = 1;</code>
     * @return The serializeType.
     */
    @Override
    public String getSerializeType() {
      Object ref = serializeType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serializeType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * hessian4
     * json
     * </pre>
     *
     * <code>string serializeType = 1;</code>
     * @return The bytes for serializeType.
     */
    @Override
    public com.google.protobuf.ByteString
        getSerializeTypeBytes() {
      Object ref = serializeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serializeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.ByteString> args_;
    /**
     * <code>repeated bytes args = 2;</code>
     * @return A list containing the args.
     */
    @Override
    public java.util.List<com.google.protobuf.ByteString>
        getArgsList() {
      return args_;
    }
    /**
     * <code>repeated bytes args = 2;</code>
     * @return The count of args.
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated bytes args = 2;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    public com.google.protobuf.ByteString getArgs(int index) {
      return args_.get(index);
    }

    public static final int ARGTYPES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList argTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string argTypes = 3;</code>
     * @return A list containing the argTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getArgTypesList() {
      return argTypes_;
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @return The count of argTypes.
     */
    public int getArgTypesCount() {
      return argTypes_.size();
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param index The index of the element to return.
     * @return The argTypes at the given index.
     */
    public String getArgTypes(int index) {
      return argTypes_.get(index);
    }
    /**
     * <code>repeated string argTypes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the argTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getArgTypesBytes(int index) {
      return argTypes_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serializeType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serializeType_);
      }
      for (int i = 0; i < args_.size(); i++) {
        output.writeBytes(2, args_.get(i));
      }
      for (int i = 0; i < argTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, argTypes_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serializeType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serializeType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < args_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(args_.get(i));
        }
        size += dataSize;
        size += 1 * getArgsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < argTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(argTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getArgTypesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper)) {
        return super.equals(obj);
      }
      org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper other = (org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper) obj;

      if (!getSerializeType()
          .equals(other.getSerializeType())) return false;
      if (!getArgsList()
          .equals(other.getArgsList())) return false;
      if (!getArgTypesList()
          .equals(other.getArgTypesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERIALIZETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSerializeType().hashCode();
      if (getArgsCount() > 0) {
        hash = (37 * hash) + ARGS_FIELD_NUMBER;
        hash = (53 * hash) + getArgsList().hashCode();
      }
      if (getArgTypesCount() > 0) {
        hash = (37 * hash) + ARGTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getArgTypesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.dubbo.triple.TripleRequestWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.apache.dubbo.triple.TripleRequestWrapper)
        org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_org_apache_dubbo_triple_TripleRequestWrapper_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_org_apache_dubbo_triple_TripleRequestWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper.class, org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper.Builder.class);
      }

      // Construct using org.apache.dubbo.org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serializeType_ = "";
        args_ = java.util.Collections.emptyList();
        argTypes_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_org_apache_dubbo_triple_TripleRequestWrapper_descriptor;
      }

      @Override
      public org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper build() {
        org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper buildPartial() {
        org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper result = new org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper result) {
        if (((bitField0_ & 0x00000002) != 0)) {
          args_ = java.util.Collections.unmodifiableList(args_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.args_ = args_;
      }

      private void buildPartial0(org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serializeType_ = serializeType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          argTypes_.makeImmutable();
          result.argTypes_ = argTypes_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper) {
          return mergeFrom((org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getSerializeType().isEmpty()) {
          serializeType_ = other.serializeType_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
        if (!other.argTypes_.isEmpty()) {
          if (argTypes_.isEmpty()) {
            argTypes_ = other.argTypes_;
            bitField0_ |= 0x00000004;
          } else {
            ensureArgTypesIsMutable();
            argTypes_.addAll(other.argTypes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                serializeType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureArgsIsMutable();
                args_.add(v);
                break;
              } // case 18
              case 26: {
                String s = input.readStringRequireUtf8();
                ensureArgTypesIsMutable();
                argTypes_.add(s);
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object serializeType_ = "";
      /**
       * <pre>
       * hessian4
       * json
       * </pre>
       *
       * <code>string serializeType = 1;</code>
       * @return The serializeType.
       */
      public String getSerializeType() {
        Object ref = serializeType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serializeType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * hessian4
       * json
       * </pre>
       *
       * <code>string serializeType = 1;</code>
       * @return The bytes for serializeType.
       */
      public com.google.protobuf.ByteString
          getSerializeTypeBytes() {
        Object ref = serializeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serializeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * hessian4
       * json
       * </pre>
       *
       * <code>string serializeType = 1;</code>
       * @param value The serializeType to set.
       * @return This builder for chaining.
       */
      public Builder setSerializeType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        serializeType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * hessian4
       * json
       * </pre>
       *
       * <code>string serializeType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerializeType() {
        serializeType_ = getDefaultInstance().getSerializeType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * hessian4
       * json
       * </pre>
       *
       * <code>string serializeType = 1;</code>
       * @param value The bytes for serializeType to set.
       * @return This builder for chaining.
       */
      public Builder setSerializeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serializeType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> args_ = java.util.Collections.emptyList();
      private void ensureArgsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          args_ = new java.util.ArrayList<com.google.protobuf.ByteString>(args_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated bytes args = 2;</code>
       * @return A list containing the args.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getArgsList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(args_) : args_;
      }
      /**
       * <code>repeated bytes args = 2;</code>
       * @return The count of args.
       */
      public int getArgsCount() {
        return args_.size();
      }
      /**
       * <code>repeated bytes args = 2;</code>
       * @param index The index of the element to return.
       * @return The args at the given index.
       */
      public com.google.protobuf.ByteString getArgs(int index) {
        return args_.get(index);
      }
      /**
       * <code>repeated bytes args = 2;</code>
       * @param index The index to set the value at.
       * @param value The args to set.
       * @return This builder for chaining.
       */
      public Builder setArgs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureArgsIsMutable();
        args_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes args = 2;</code>
       * @param value The args to add.
       * @return This builder for chaining.
       */
      public Builder addArgs(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes args = 2;</code>
       * @param values The args to add.
       * @return This builder for chaining.
       */
      public Builder addAllArgs(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, args_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes args = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearArgs() {
        args_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList argTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureArgTypesIsMutable() {
        if (!argTypes_.isModifiable()) {
          argTypes_ = new com.google.protobuf.LazyStringArrayList(argTypes_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated string argTypes = 3;</code>
       * @return A list containing the argTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getArgTypesList() {
        argTypes_.makeImmutable();
        return argTypes_;
      }
      /**
       * <code>repeated string argTypes = 3;</code>
       * @return The count of argTypes.
       */
      public int getArgTypesCount() {
        return argTypes_.size();
      }
      /**
       * <code>repeated string argTypes = 3;</code>
       * @param index The index of the element to return.
       * @return The argTypes at the given index.
       */
      public String getArgTypes(int index) {
        return argTypes_.get(index);
      }
      /**
       * <code>repeated string argTypes = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the argTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getArgTypesBytes(int index) {
        return argTypes_.getByteString(index);
      }
      /**
       * <code>repeated string argTypes = 3;</code>
       * @param index The index to set the value at.
       * @param value The argTypes to set.
       * @return This builder for chaining.
       */
      public Builder setArgTypes(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureArgTypesIsMutable();
        argTypes_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string argTypes = 3;</code>
       * @param value The argTypes to add.
       * @return This builder for chaining.
       */
      public Builder addArgTypes(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureArgTypesIsMutable();
        argTypes_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string argTypes = 3;</code>
       * @param values The argTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllArgTypes(
          Iterable<String> values) {
        ensureArgTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, argTypes_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string argTypes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearArgTypes() {
        argTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string argTypes = 3;</code>
       * @param value The bytes of the argTypes to add.
       * @return This builder for chaining.
       */
      public Builder addArgTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureArgTypesIsMutable();
        argTypes_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.apache.dubbo.triple.TripleRequestWrapper)
    }

    // @@protoc_insertion_point(class_scope:org.apache.dubbo.triple.TripleRequestWrapper)
    private static final org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper();
    }

    public static org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TripleRequestWrapper>
        PARSER = new com.google.protobuf.AbstractParser<TripleRequestWrapper>() {
      @Override
      public TripleRequestWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TripleRequestWrapper> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TripleRequestWrapper> getParserForType() {
      return PARSER;
    }

    @Override
    public org.apache.dubbo.triple.TripleWrapper.TripleRequestWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TripleResponseWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.apache.dubbo.triple.TripleResponseWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string serializeType = 1;</code>
     * @return The serializeType.
     */
    String getSerializeType();
    /**
     * <code>string serializeType = 1;</code>
     * @return The bytes for serializeType.
     */
    com.google.protobuf.ByteString
        getSerializeTypeBytes();

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>string type = 3;</code>
     * @return The type.
     */
    String getType();
    /**
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code org.apache.dubbo.triple.TripleResponseWrapper}
   */
  public static final class TripleResponseWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.apache.dubbo.triple.TripleResponseWrapper)
      TripleResponseWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TripleResponseWrapper.newBuilder() to construct.
    private TripleResponseWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TripleResponseWrapper() {
      serializeType_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      type_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TripleResponseWrapper();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_org_apache_dubbo_triple_TripleResponseWrapper_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_org_apache_dubbo_triple_TripleResponseWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper.class, org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper.Builder.class);
    }

    public static final int SERIALIZETYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object serializeType_ = "";
    /**
     * <code>string serializeType = 1;</code>
     * @return The serializeType.
     */
    @Override
    public String getSerializeType() {
      Object ref = serializeType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serializeType_ = s;
        return s;
      }
    }
    /**
     * <code>string serializeType = 1;</code>
     * @return The bytes for serializeType.
     */
    @Override
    public com.google.protobuf.ByteString
        getSerializeTypeBytes() {
      Object ref = serializeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serializeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object type_ = "";
    /**
     * <code>string type = 3;</code>
     * @return The type.
     */
    @Override
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    @Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serializeType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serializeType_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serializeType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serializeType_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper)) {
        return super.equals(obj);
      }
      org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper other = (org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper) obj;

      if (!getSerializeType()
          .equals(other.getSerializeType())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERIALIZETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSerializeType().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.dubbo.triple.TripleResponseWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.apache.dubbo.triple.TripleResponseWrapper)
        org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_org_apache_dubbo_triple_TripleResponseWrapper_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_org_apache_dubbo_triple_TripleResponseWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper.class, org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper.Builder.class);
      }

      // Construct using org.apache.dubbo.org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serializeType_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
        type_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_org_apache_dubbo_triple_TripleResponseWrapper_descriptor;
      }

      @Override
      public org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper build() {
        org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper buildPartial() {
        org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper result = new org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serializeType_ = serializeType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.data_ = data_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper) {
          return mergeFrom((org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getSerializeType().isEmpty()) {
          serializeType_ = other.serializeType_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                serializeType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object serializeType_ = "";
      /**
       * <code>string serializeType = 1;</code>
       * @return The serializeType.
       */
      public String getSerializeType() {
        Object ref = serializeType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serializeType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serializeType = 1;</code>
       * @return The bytes for serializeType.
       */
      public com.google.protobuf.ByteString
          getSerializeTypeBytes() {
        Object ref = serializeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serializeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serializeType = 1;</code>
       * @param value The serializeType to set.
       * @return This builder for chaining.
       */
      public Builder setSerializeType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        serializeType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string serializeType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerializeType() {
        serializeType_ = getDefaultInstance().getSerializeType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string serializeType = 1;</code>
       * @param value The bytes for serializeType to set.
       * @return This builder for chaining.
       */
      public Builder setSerializeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serializeType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <code>string type = 3;</code>
       * @return The type.
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.apache.dubbo.triple.TripleResponseWrapper)
    }

    // @@protoc_insertion_point(class_scope:org.apache.dubbo.triple.TripleResponseWrapper)
    private static final org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper();
    }

    public static org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TripleResponseWrapper>
        PARSER = new com.google.protobuf.AbstractParser<TripleResponseWrapper>() {
      @Override
      public TripleResponseWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TripleResponseWrapper> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TripleResponseWrapper> getParserForType() {
      return PARSER;
    }

    @Override
    public org.apache.dubbo.triple.TripleWrapper.TripleResponseWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TripleExceptionWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.apache.dubbo.triple.TripleExceptionWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string language = 1;</code>
     * @return The language.
     */
    String getLanguage();
    /**
     * <code>string language = 1;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <code>string serialization = 2;</code>
     * @return The serialization.
     */
    String getSerialization();
    /**
     * <code>string serialization = 2;</code>
     * @return The bytes for serialization.
     */
    com.google.protobuf.ByteString
        getSerializationBytes();

    /**
     * <code>string className = 3;</code>
     * @return The className.
     */
    String getClassName();
    /**
     * <code>string className = 3;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code org.apache.dubbo.triple.TripleExceptionWrapper}
   */
  public static final class TripleExceptionWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.apache.dubbo.triple.TripleExceptionWrapper)
      TripleExceptionWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TripleExceptionWrapper.newBuilder() to construct.
    private TripleExceptionWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TripleExceptionWrapper() {
      language_ = "";
      serialization_ = "";
      className_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TripleExceptionWrapper();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper.class, org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper.Builder.class);
    }

    public static final int LANGUAGE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object language_ = "";
    /**
     * <code>string language = 1;</code>
     * @return The language.
     */
    @Override
    public String getLanguage() {
      Object ref = language_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <code>string language = 1;</code>
     * @return The bytes for language.
     */
    @Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERIALIZATION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object serialization_ = "";
    /**
     * <code>string serialization = 2;</code>
     * @return The serialization.
     */
    @Override
    public String getSerialization() {
      Object ref = serialization_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serialization_ = s;
        return s;
      }
    }
    /**
     * <code>string serialization = 2;</code>
     * @return The bytes for serialization.
     */
    @Override
    public com.google.protobuf.ByteString
        getSerializationBytes() {
      Object ref = serialization_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serialization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object className_ = "";
    /**
     * <code>string className = 3;</code>
     * @return The className.
     */
    @Override
    public String getClassName() {
      Object ref = className_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <code>string className = 3;</code>
     * @return The bytes for className.
     */
    @Override
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      Object ref = className_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, language_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serialization_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serialization_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, className_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, language_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serialization_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serialization_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, className_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper)) {
        return super.equals(obj);
      }
      org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper other = (org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper) obj;

      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (!getSerialization()
          .equals(other.getSerialization())) return false;
      if (!getClassName()
          .equals(other.getClassName())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (37 * hash) + SERIALIZATION_FIELD_NUMBER;
      hash = (53 * hash) + getSerialization().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.dubbo.triple.TripleExceptionWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.apache.dubbo.triple.TripleExceptionWrapper)
        org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper.class, org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper.Builder.class);
      }

      // Construct using org.apache.dubbo.org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        language_ = "";
        serialization_ = "";
        className_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_descriptor;
      }

      @Override
      public org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper build() {
        org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper buildPartial() {
        org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper result = new org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.language_ = language_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serialization_ = serialization_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.className_ = className_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.data_ = data_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper) {
          return mergeFrom((org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getSerialization().isEmpty()) {
          serialization_ = other.serialization_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                language_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                serialization_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                className_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object language_ = "";
      /**
       * <code>string language = 1;</code>
       * @return The language.
       */
      public String getLanguage() {
        Object ref = language_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string language = 1;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string language = 1;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        language_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string language = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        language_ = getDefaultInstance().getLanguage();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string language = 1;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        language_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object serialization_ = "";
      /**
       * <code>string serialization = 2;</code>
       * @return The serialization.
       */
      public String getSerialization() {
        Object ref = serialization_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serialization_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serialization = 2;</code>
       * @return The bytes for serialization.
       */
      public com.google.protobuf.ByteString
          getSerializationBytes() {
        Object ref = serialization_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serialization_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serialization = 2;</code>
       * @param value The serialization to set.
       * @return This builder for chaining.
       */
      public Builder setSerialization(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        serialization_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string serialization = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerialization() {
        serialization_ = getDefaultInstance().getSerialization();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string serialization = 2;</code>
       * @param value The bytes for serialization to set.
       * @return This builder for chaining.
       */
      public Builder setSerializationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serialization_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object className_ = "";
      /**
       * <code>string className = 3;</code>
       * @return The className.
       */
      public String getClassName() {
        Object ref = className_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string className = 3;</code>
       * @return The bytes for className.
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string className = 3;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        className_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string className = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        className_ = getDefaultInstance().getClassName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string className = 3;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        className_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 4;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.apache.dubbo.triple.TripleExceptionWrapper)
    }

    // @@protoc_insertion_point(class_scope:org.apache.dubbo.triple.TripleExceptionWrapper)
    private static final org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper();
    }

    public static org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TripleExceptionWrapper>
        PARSER = new com.google.protobuf.AbstractParser<TripleExceptionWrapper>() {
      @Override
      public TripleExceptionWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TripleExceptionWrapper> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TripleExceptionWrapper> getParserForType() {
      return PARSER;
    }

    @Override
    public org.apache.dubbo.triple.TripleWrapper.TripleExceptionWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_dubbo_triple_TripleRequestWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_dubbo_triple_TripleRequestWrapper_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_dubbo_triple_TripleResponseWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_dubbo_triple_TripleResponseWrapper_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024triple_wrapper.proto\022\027org.apache.dubbo" +
      ".triple\"M\n\024TripleRequestWrapper\022\025\n\rseria" +
      "lizeType\030\001 \001(\t\022\014\n\004args\030\002 \003(\014\022\020\n\010argTypes" +
      "\030\003 \003(\t\"J\n\025TripleResponseWrapper\022\025\n\rseria" +
      "lizeType\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\022\014\n\004type\030\003 \001" +
      "(\t\"b\n\026TripleExceptionWrapper\022\020\n\010language" +
      "\030\001 \001(\t\022\025\n\rserialization\030\002 \001(\t\022\021\n\tclassNa" +
      "me\030\003 \001(\t\022\014\n\004data\030\004 \001(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_apache_dubbo_triple_TripleRequestWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_apache_dubbo_triple_TripleRequestWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_dubbo_triple_TripleRequestWrapper_descriptor,
        new String[] { "SerializeType", "Args", "ArgTypes", });
    internal_static_org_apache_dubbo_triple_TripleResponseWrapper_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_apache_dubbo_triple_TripleResponseWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_dubbo_triple_TripleResponseWrapper_descriptor,
        new String[] { "SerializeType", "Data", "Type", });
    internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_dubbo_triple_TripleExceptionWrapper_descriptor,
        new String[] { "Language", "Serialization", "ClassName", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
