// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reflectionV1Alpha.proto

package io.grpc.reflection.v1alpha;

/**
 * <pre>
 * Serialized FileDescriptorProto messages sent by the server answering
 * a file_by_filename, file_containing_symbol, or file_containing_extension
 * request.
 * </pre>
 *
 * Protobuf type {@code grpc.reflection.v1alpha.FileDescriptorResponse}
 */
public final class FileDescriptorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.FileDescriptorResponse)
    FileDescriptorResponseOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use FileDescriptorResponse.newBuilder() to construct.
    private FileDescriptorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    private FileDescriptorResponse() {
        fileDescriptorProto_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
        return new FileDescriptorResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_FileDescriptorResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_FileDescriptorResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.reflection.v1alpha.FileDescriptorResponse.class, io.grpc.reflection.v1alpha.FileDescriptorResponse.Builder.class);
    }

    public static final int FILE_DESCRIPTOR_PROTO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.ByteString> fileDescriptorProto_;
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @return A list containing the fileDescriptorProto.
     */
    @Override
    public java.util.List<com.google.protobuf.ByteString>
    getFileDescriptorProtoList() {
        return fileDescriptorProto_;
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @return The count of fileDescriptorProto.
     */
    public int getFileDescriptorProtoCount() {
        return fileDescriptorProto_.size();
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     * </pre>
     *
     * <code>repeated bytes file_descriptor_proto = 1;</code>
     * @param index The index of the element to return.
     * @return The fileDescriptorProto at the given index.
     */
    public com.google.protobuf.ByteString getFileDescriptorProto(int index) {
        return fileDescriptorProto_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        for (int i = 0; i < fileDescriptorProto_.size(); i++) {
            output.writeBytes(1, fileDescriptorProto_.get(i));
        }
        getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
            int dataSize = 0;
            for (int i = 0; i < fileDescriptorProto_.size(); i++) {
                dataSize += com.google.protobuf.CodedOutputStream
                    .computeBytesSizeNoTag(fileDescriptorProto_.get(i));
            }
            size += dataSize;
            size += 1 * getFileDescriptorProtoList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof io.grpc.reflection.v1alpha.FileDescriptorResponse)) {
            return super.equals(obj);
        }
        io.grpc.reflection.v1alpha.FileDescriptorResponse other = (io.grpc.reflection.v1alpha.FileDescriptorResponse) obj;

        if (!getFileDescriptorProtoList()
            .equals(other.getFileDescriptorProtoList())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getFileDescriptorProtoCount() > 0) {
            hash = (37 * hash) + FILE_DESCRIPTOR_PROTO_FIELD_NUMBER;
            hash = (53 * hash) + getFileDescriptorProtoList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }
    public static io.grpc.reflection.v1alpha.FileDescriptorResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.reflection.v1alpha.FileDescriptorResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * <pre>
     * Serialized FileDescriptorProto messages sent by the server answering
     * a file_by_filename, file_containing_symbol, or file_containing_extension
     * request.
     * </pre>
     *
     * Protobuf type {@code grpc.reflection.v1alpha.FileDescriptorResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.FileDescriptorResponse)
        FileDescriptorResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_FileDescriptorResponse_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_FileDescriptorResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    io.grpc.reflection.v1alpha.FileDescriptorResponse.class, io.grpc.reflection.v1alpha.FileDescriptorResponse.Builder.class);
        }

        // Construct using io.grpc.reflection.v1alpha.FileDescriptorResponse.newBuilder()
        private Builder() {

        }

        private Builder(
            BuilderParent parent) {
            super(parent);

        }
        @Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            fileDescriptorProto_ = java.util.Collections.emptyList();
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_FileDescriptorResponse_descriptor;
        }

        @Override
        public io.grpc.reflection.v1alpha.FileDescriptorResponse getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public io.grpc.reflection.v1alpha.FileDescriptorResponse build() {
            io.grpc.reflection.v1alpha.FileDescriptorResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public io.grpc.reflection.v1alpha.FileDescriptorResponse buildPartial() {
            io.grpc.reflection.v1alpha.FileDescriptorResponse result = new io.grpc.reflection.v1alpha.FileDescriptorResponse(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) { buildPartial0(result); }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(io.grpc.reflection.v1alpha.FileDescriptorResponse result) {
            if (((bitField0_ & 0x00000001) != 0)) {
                fileDescriptorProto_ = java.util.Collections.unmodifiableList(fileDescriptorProto_);
                bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.fileDescriptorProto_ = fileDescriptorProto_;
        }

        private void buildPartial0(io.grpc.reflection.v1alpha.FileDescriptorResponse result) {
            int from_bitField0_ = bitField0_;
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof io.grpc.reflection.v1alpha.FileDescriptorResponse) {
                return mergeFrom((io.grpc.reflection.v1alpha.FileDescriptorResponse)other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(io.grpc.reflection.v1alpha.FileDescriptorResponse other) {
            if (other == getDefaultInstance()) return this;
            if (!other.fileDescriptorProto_.isEmpty()) {
                if (fileDescriptorProto_.isEmpty()) {
                    fileDescriptorProto_ = other.fileDescriptorProto_;
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    ensureFileDescriptorProtoIsMutable();
                    fileDescriptorProto_.addAll(other.fileDescriptorProto_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString v = input.readBytes();
                            ensureFileDescriptorProtoIsMutable();
                            fileDescriptorProto_.add(v);
                            break;
                        } // case 10
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }
        private int bitField0_;

        private java.util.List<com.google.protobuf.ByteString> fileDescriptorProto_ = java.util.Collections.emptyList();
        private void ensureFileDescriptorProtoIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                fileDescriptorProto_ = new java.util.ArrayList<com.google.protobuf.ByteString>(fileDescriptorProto_);
                bitField0_ |= 0x00000001;
            }
        }
        /**
         * <pre>
         * Serialized FileDescriptorProto messages. We avoid taking a dependency on
         * descriptor.proto, which uses proto2 only features, by making them opaque
         * bytes instead.
         * </pre>
         *
         * <code>repeated bytes file_descriptor_proto = 1;</code>
         * @return A list containing the fileDescriptorProto.
         */
        public java.util.List<com.google.protobuf.ByteString>
        getFileDescriptorProtoList() {
            return ((bitField0_ & 0x00000001) != 0) ?
                java.util.Collections.unmodifiableList(fileDescriptorProto_) : fileDescriptorProto_;
        }
        /**
         * <pre>
         * Serialized FileDescriptorProto messages. We avoid taking a dependency on
         * descriptor.proto, which uses proto2 only features, by making them opaque
         * bytes instead.
         * </pre>
         *
         * <code>repeated bytes file_descriptor_proto = 1;</code>
         * @return The count of fileDescriptorProto.
         */
        public int getFileDescriptorProtoCount() {
            return fileDescriptorProto_.size();
        }
        /**
         * <pre>
         * Serialized FileDescriptorProto messages. We avoid taking a dependency on
         * descriptor.proto, which uses proto2 only features, by making them opaque
         * bytes instead.
         * </pre>
         *
         * <code>repeated bytes file_descriptor_proto = 1;</code>
         * @param index The index of the element to return.
         * @return The fileDescriptorProto at the given index.
         */
        public com.google.protobuf.ByteString getFileDescriptorProto(int index) {
            return fileDescriptorProto_.get(index);
        }
        /**
         * <pre>
         * Serialized FileDescriptorProto messages. We avoid taking a dependency on
         * descriptor.proto, which uses proto2 only features, by making them opaque
         * bytes instead.
         * </pre>
         *
         * <code>repeated bytes file_descriptor_proto = 1;</code>
         * @param index The index to set the value at.
         * @param value The fileDescriptorProto to set.
         * @return This builder for chaining.
         */
        public Builder setFileDescriptorProto(
            int index, com.google.protobuf.ByteString value) {
            if (value == null) { throw new NullPointerException(); }
            ensureFileDescriptorProtoIsMutable();
            fileDescriptorProto_.set(index, value);
            onChanged();
            return this;
        }
        /**
         * <pre>
         * Serialized FileDescriptorProto messages. We avoid taking a dependency on
         * descriptor.proto, which uses proto2 only features, by making them opaque
         * bytes instead.
         * </pre>
         *
         * <code>repeated bytes file_descriptor_proto = 1;</code>
         * @param value The fileDescriptorProto to add.
         * @return This builder for chaining.
         */
        public Builder addFileDescriptorProto(com.google.protobuf.ByteString value) {
            if (value == null) { throw new NullPointerException(); }
            ensureFileDescriptorProtoIsMutable();
            fileDescriptorProto_.add(value);
            onChanged();
            return this;
        }
        /**
         * <pre>
         * Serialized FileDescriptorProto messages. We avoid taking a dependency on
         * descriptor.proto, which uses proto2 only features, by making them opaque
         * bytes instead.
         * </pre>
         *
         * <code>repeated bytes file_descriptor_proto = 1;</code>
         * @param values The fileDescriptorProto to add.
         * @return This builder for chaining.
         */
        public Builder addAllFileDescriptorProto(
            Iterable<? extends com.google.protobuf.ByteString> values) {
            ensureFileDescriptorProtoIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, fileDescriptorProto_);
            onChanged();
            return this;
        }
        /**
         * <pre>
         * Serialized FileDescriptorProto messages. We avoid taking a dependency on
         * descriptor.proto, which uses proto2 only features, by making them opaque
         * bytes instead.
         * </pre>
         *
         * <code>repeated bytes file_descriptor_proto = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearFileDescriptorProto() {
            fileDescriptorProto_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.FileDescriptorResponse)
    }

    // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.FileDescriptorResponse)
    private static final io.grpc.reflection.v1alpha.FileDescriptorResponse DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new io.grpc.reflection.v1alpha.FileDescriptorResponse();
    }

    public static io.grpc.reflection.v1alpha.FileDescriptorResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileDescriptorResponse>
        PARSER = new com.google.protobuf.AbstractParser<FileDescriptorResponse>() {
        @Override
        public FileDescriptorResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                    .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<FileDescriptorResponse> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FileDescriptorResponse> getParserForType() {
        return PARSER;
    }

    @Override
    public io.grpc.reflection.v1alpha.FileDescriptorResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

