// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reflectionV1Alpha.proto

package io.grpc.reflection.v1alpha;

/**
 * <pre>
 * The message sent by the server to answer ServerReflectionInfo method.
 * </pre>
 *
 * Protobuf type {@code grpc.reflection.v1alpha.ServerReflectionResponse}
 */
public final class ServerReflectionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.ServerReflectionResponse)
    ServerReflectionResponseOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use ServerReflectionResponse.newBuilder() to construct.
    private ServerReflectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    private ServerReflectionResponse() {
        validHost_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
        return new ServerReflectionResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.reflection.v1alpha.ServerReflectionResponse.class, io.grpc.reflection.v1alpha.ServerReflectionResponse.Builder.class);
    }

    private int messageResponseCase_ = 0;
    @SuppressWarnings("serial")
    private Object messageResponse_;
    public enum MessageResponseCase
        implements com.google.protobuf.Internal.EnumLite,
        InternalOneOfEnum {
        FILE_DESCRIPTOR_RESPONSE(4),
        ALL_EXTENSION_NUMBERS_RESPONSE(5),
        LIST_SERVICES_RESPONSE(6),
        ERROR_RESPONSE(7),
        MESSAGERESPONSE_NOT_SET(0);
        private final int value;
        private MessageResponseCase(int value) {
            this.value = value;
        }
        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static MessageResponseCase valueOf(int value) {
            return forNumber(value);
        }

        public static MessageResponseCase forNumber(int value) {
            switch (value) {
                case 4: return FILE_DESCRIPTOR_RESPONSE;
                case 5: return ALL_EXTENSION_NUMBERS_RESPONSE;
                case 6: return LIST_SERVICES_RESPONSE;
                case 7: return ERROR_RESPONSE;
                case 0: return MESSAGERESPONSE_NOT_SET;
                default: return null;
            }
        }
        public int getNumber() {
            return this.value;
        }
    };

    public MessageResponseCase
    getMessageResponseCase() {
        return MessageResponseCase.forNumber(
            messageResponseCase_);
    }

    public static final int VALID_HOST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object validHost_ = "";
    /**
     * <code>string valid_host = 1;</code>
     * @return The validHost.
     */
    @Override
    public String getValidHost() {
        Object ref = validHost_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            validHost_ = s;
            return s;
        }
    }
    /**
     * <code>string valid_host = 1;</code>
     * @return The bytes for validHost.
     */
    @Override
    public com.google.protobuf.ByteString
    getValidHostBytes() {
        Object ref = validHost_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            validHost_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ORIGINAL_REQUEST_FIELD_NUMBER = 2;
    private io.grpc.reflection.v1alpha.ServerReflectionRequest originalRequest_;
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     * @return Whether the originalRequest field is set.
     */
    @Override
    public boolean hasOriginalRequest() {
        return originalRequest_ != null;
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     * @return The originalRequest.
     */
    @Override
    public io.grpc.reflection.v1alpha.ServerReflectionRequest getOriginalRequest() {
        return originalRequest_ == null ? io.grpc.reflection.v1alpha.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     */
    @Override
    public io.grpc.reflection.v1alpha.ServerReflectionRequestOrBuilder getOriginalRequestOrBuilder() {
        return originalRequest_ == null ? io.grpc.reflection.v1alpha.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
    }

    public static final int FILE_DESCRIPTOR_RESPONSE_FIELD_NUMBER = 4;
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     * @return Whether the fileDescriptorResponse field is set.
     */
    @Override
    public boolean hasFileDescriptorResponse() {
        return messageResponseCase_ == 4;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     * @return The fileDescriptorResponse.
     */
    @Override
    public io.grpc.reflection.v1alpha.FileDescriptorResponse getFileDescriptorResponse() {
        if (messageResponseCase_ == 4) {
            return (io.grpc.reflection.v1alpha.FileDescriptorResponse) messageResponse_;
        }
        return io.grpc.reflection.v1alpha.FileDescriptorResponse.getDefaultInstance();
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    @Override
    public io.grpc.reflection.v1alpha.FileDescriptorResponseOrBuilder getFileDescriptorResponseOrBuilder() {
        if (messageResponseCase_ == 4) {
            return (io.grpc.reflection.v1alpha.FileDescriptorResponse) messageResponse_;
        }
        return io.grpc.reflection.v1alpha.FileDescriptorResponse.getDefaultInstance();
    }

    public static final int ALL_EXTENSION_NUMBERS_RESPONSE_FIELD_NUMBER = 5;
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     * @return Whether the allExtensionNumbersResponse field is set.
     */
    @Override
    public boolean hasAllExtensionNumbersResponse() {
        return messageResponseCase_ == 5;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     * @return The allExtensionNumbersResponse.
     */
    @Override
    public io.grpc.reflection.v1alpha.ExtensionNumberResponse getAllExtensionNumbersResponse() {
        if (messageResponseCase_ == 5) {
            return (io.grpc.reflection.v1alpha.ExtensionNumberResponse) messageResponse_;
        }
        return io.grpc.reflection.v1alpha.ExtensionNumberResponse.getDefaultInstance();
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    @Override
    public io.grpc.reflection.v1alpha.ExtensionNumberResponseOrBuilder getAllExtensionNumbersResponseOrBuilder() {
        if (messageResponseCase_ == 5) {
            return (io.grpc.reflection.v1alpha.ExtensionNumberResponse) messageResponse_;
        }
        return io.grpc.reflection.v1alpha.ExtensionNumberResponse.getDefaultInstance();
    }

    public static final int LIST_SERVICES_RESPONSE_FIELD_NUMBER = 6;
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     * @return Whether the listServicesResponse field is set.
     */
    @Override
    public boolean hasListServicesResponse() {
        return messageResponseCase_ == 6;
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     * @return The listServicesResponse.
     */
    @Override
    public io.grpc.reflection.v1alpha.ListServiceResponse getListServicesResponse() {
        if (messageResponseCase_ == 6) {
            return (io.grpc.reflection.v1alpha.ListServiceResponse) messageResponse_;
        }
        return io.grpc.reflection.v1alpha.ListServiceResponse.getDefaultInstance();
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     */
    @Override
    public io.grpc.reflection.v1alpha.ListServiceResponseOrBuilder getListServicesResponseOrBuilder() {
        if (messageResponseCase_ == 6) {
            return (io.grpc.reflection.v1alpha.ListServiceResponse) messageResponse_;
        }
        return io.grpc.reflection.v1alpha.ListServiceResponse.getDefaultInstance();
    }

    public static final int ERROR_RESPONSE_FIELD_NUMBER = 7;
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     * @return Whether the errorResponse field is set.
     */
    @Override
    public boolean hasErrorResponse() {
        return messageResponseCase_ == 7;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     * @return The errorResponse.
     */
    @Override
    public io.grpc.reflection.v1alpha.ErrorResponse getErrorResponse() {
        if (messageResponseCase_ == 7) {
            return (io.grpc.reflection.v1alpha.ErrorResponse) messageResponse_;
        }
        return io.grpc.reflection.v1alpha.ErrorResponse.getDefaultInstance();
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     */
    @Override
    public io.grpc.reflection.v1alpha.ErrorResponseOrBuilder getErrorResponseOrBuilder() {
        if (messageResponseCase_ == 7) {
            return (io.grpc.reflection.v1alpha.ErrorResponse) messageResponse_;
        }
        return io.grpc.reflection.v1alpha.ErrorResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validHost_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, validHost_);
        }
        if (originalRequest_ != null) {
            output.writeMessage(2, getOriginalRequest());
        }
        if (messageResponseCase_ == 4) {
            output.writeMessage(4, (io.grpc.reflection.v1alpha.FileDescriptorResponse) messageResponse_);
        }
        if (messageResponseCase_ == 5) {
            output.writeMessage(5, (io.grpc.reflection.v1alpha.ExtensionNumberResponse) messageResponse_);
        }
        if (messageResponseCase_ == 6) {
            output.writeMessage(6, (io.grpc.reflection.v1alpha.ListServiceResponse) messageResponse_);
        }
        if (messageResponseCase_ == 7) {
            output.writeMessage(7, (io.grpc.reflection.v1alpha.ErrorResponse) messageResponse_);
        }
        getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validHost_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, validHost_);
        }
        if (originalRequest_ != null) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(2, getOriginalRequest());
        }
        if (messageResponseCase_ == 4) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(4, (io.grpc.reflection.v1alpha.FileDescriptorResponse) messageResponse_);
        }
        if (messageResponseCase_ == 5) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(5, (io.grpc.reflection.v1alpha.ExtensionNumberResponse) messageResponse_);
        }
        if (messageResponseCase_ == 6) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(6, (io.grpc.reflection.v1alpha.ListServiceResponse) messageResponse_);
        }
        if (messageResponseCase_ == 7) {
            size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(7, (io.grpc.reflection.v1alpha.ErrorResponse) messageResponse_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof io.grpc.reflection.v1alpha.ServerReflectionResponse)) {
            return super.equals(obj);
        }
        io.grpc.reflection.v1alpha.ServerReflectionResponse other = (io.grpc.reflection.v1alpha.ServerReflectionResponse) obj;

        if (!getValidHost()
            .equals(other.getValidHost())) return false;
        if (hasOriginalRequest() != other.hasOriginalRequest()) return false;
        if (hasOriginalRequest()) {
            if (!getOriginalRequest()
                .equals(other.getOriginalRequest())) return false;
        }
        if (!getMessageResponseCase().equals(other.getMessageResponseCase())) return false;
        switch (messageResponseCase_) {
            case 4:
                if (!getFileDescriptorResponse()
                    .equals(other.getFileDescriptorResponse())) return false;
                break;
            case 5:
                if (!getAllExtensionNumbersResponse()
                    .equals(other.getAllExtensionNumbersResponse())) return false;
                break;
            case 6:
                if (!getListServicesResponse()
                    .equals(other.getListServicesResponse())) return false;
                break;
            case 7:
                if (!getErrorResponse()
                    .equals(other.getErrorResponse())) return false;
                break;
            case 0:
            default:
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + VALID_HOST_FIELD_NUMBER;
        hash = (53 * hash) + getValidHost().hashCode();
        if (hasOriginalRequest()) {
            hash = (37 * hash) + ORIGINAL_REQUEST_FIELD_NUMBER;
            hash = (53 * hash) + getOriginalRequest().hashCode();
        }
        switch (messageResponseCase_) {
            case 4:
                hash = (37 * hash) + FILE_DESCRIPTOR_RESPONSE_FIELD_NUMBER;
                hash = (53 * hash) + getFileDescriptorResponse().hashCode();
                break;
            case 5:
                hash = (37 * hash) + ALL_EXTENSION_NUMBERS_RESPONSE_FIELD_NUMBER;
                hash = (53 * hash) + getAllExtensionNumbersResponse().hashCode();
                break;
            case 6:
                hash = (37 * hash) + LIST_SERVICES_RESPONSE_FIELD_NUMBER;
                hash = (53 * hash) + getListServicesResponse().hashCode();
                break;
            case 7:
                hash = (37 * hash) + ERROR_RESPONSE_FIELD_NUMBER;
                hash = (53 * hash) + getErrorResponse().hashCode();
                break;
            case 0:
            default:
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }
    public static io.grpc.reflection.v1alpha.ServerReflectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.reflection.v1alpha.ServerReflectionResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * <pre>
     * The message sent by the server to answer ServerReflectionInfo method.
     * </pre>
     *
     * Protobuf type {@code grpc.reflection.v1alpha.ServerReflectionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.ServerReflectionResponse)
        ServerReflectionResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    io.grpc.reflection.v1alpha.ServerReflectionResponse.class, io.grpc.reflection.v1alpha.ServerReflectionResponse.Builder.class);
        }

        // Construct using io.grpc.reflection.v1alpha.ServerReflectionResponse.newBuilder()
        private Builder() {

        }

        private Builder(
            BuilderParent parent) {
            super(parent);

        }
        @Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            validHost_ = "";
            originalRequest_ = null;
            if (originalRequestBuilder_ != null) {
                originalRequestBuilder_.dispose();
                originalRequestBuilder_ = null;
            }
            if (fileDescriptorResponseBuilder_ != null) {
                fileDescriptorResponseBuilder_.clear();
            }
            if (allExtensionNumbersResponseBuilder_ != null) {
                allExtensionNumbersResponseBuilder_.clear();
            }
            if (listServicesResponseBuilder_ != null) {
                listServicesResponseBuilder_.clear();
            }
            if (errorResponseBuilder_ != null) {
                errorResponseBuilder_.clear();
            }
            messageResponseCase_ = 0;
            messageResponse_ = null;
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return io.grpc.reflection.v1alpha.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_descriptor;
        }

        @Override
        public io.grpc.reflection.v1alpha.ServerReflectionResponse getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public io.grpc.reflection.v1alpha.ServerReflectionResponse build() {
            io.grpc.reflection.v1alpha.ServerReflectionResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public io.grpc.reflection.v1alpha.ServerReflectionResponse buildPartial() {
            io.grpc.reflection.v1alpha.ServerReflectionResponse result = new io.grpc.reflection.v1alpha.ServerReflectionResponse(this);
            if (bitField0_ != 0) { buildPartial0(result); }
            buildPartialOneofs(result);
            onBuilt();
            return result;
        }

        private void buildPartial0(io.grpc.reflection.v1alpha.ServerReflectionResponse result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.validHost_ = validHost_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.originalRequest_ = originalRequestBuilder_ == null
                    ? originalRequest_
                    : originalRequestBuilder_.build();
            }
        }

        private void buildPartialOneofs(io.grpc.reflection.v1alpha.ServerReflectionResponse result) {
            result.messageResponseCase_ = messageResponseCase_;
            result.messageResponse_ = this.messageResponse_;
            if (messageResponseCase_ == 4 &&
                fileDescriptorResponseBuilder_ != null) {
                result.messageResponse_ = fileDescriptorResponseBuilder_.build();
            }
            if (messageResponseCase_ == 5 &&
                allExtensionNumbersResponseBuilder_ != null) {
                result.messageResponse_ = allExtensionNumbersResponseBuilder_.build();
            }
            if (messageResponseCase_ == 6 &&
                listServicesResponseBuilder_ != null) {
                result.messageResponse_ = listServicesResponseBuilder_.build();
            }
            if (messageResponseCase_ == 7 &&
                errorResponseBuilder_ != null) {
                result.messageResponse_ = errorResponseBuilder_.build();
            }
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof io.grpc.reflection.v1alpha.ServerReflectionResponse) {
                return mergeFrom((io.grpc.reflection.v1alpha.ServerReflectionResponse)other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(io.grpc.reflection.v1alpha.ServerReflectionResponse other) {
            if (other == getDefaultInstance()) return this;
            if (!other.getValidHost().isEmpty()) {
                validHost_ = other.validHost_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (other.hasOriginalRequest()) {
                mergeOriginalRequest(other.getOriginalRequest());
            }
            switch (other.getMessageResponseCase()) {
                case FILE_DESCRIPTOR_RESPONSE: {
                    mergeFileDescriptorResponse(other.getFileDescriptorResponse());
                    break;
                }
                case ALL_EXTENSION_NUMBERS_RESPONSE: {
                    mergeAllExtensionNumbersResponse(other.getAllExtensionNumbersResponse());
                    break;
                }
                case LIST_SERVICES_RESPONSE: {
                    mergeListServicesResponse(other.getListServicesResponse());
                    break;
                }
                case ERROR_RESPONSE: {
                    mergeErrorResponse(other.getErrorResponse());
                    break;
                }
                case MESSAGERESPONSE_NOT_SET: {
                    break;
                }
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            validHost_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            input.readMessage(
                                getOriginalRequestFieldBuilder().getBuilder(),
                                extensionRegistry);
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 34: {
                            input.readMessage(
                                getFileDescriptorResponseFieldBuilder().getBuilder(),
                                extensionRegistry);
                            messageResponseCase_ = 4;
                            break;
                        } // case 34
                        case 42: {
                            input.readMessage(
                                getAllExtensionNumbersResponseFieldBuilder().getBuilder(),
                                extensionRegistry);
                            messageResponseCase_ = 5;
                            break;
                        } // case 42
                        case 50: {
                            input.readMessage(
                                getListServicesResponseFieldBuilder().getBuilder(),
                                extensionRegistry);
                            messageResponseCase_ = 6;
                            break;
                        } // case 50
                        case 58: {
                            input.readMessage(
                                getErrorResponseFieldBuilder().getBuilder(),
                                extensionRegistry);
                            messageResponseCase_ = 7;
                            break;
                        } // case 58
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }
        private int messageResponseCase_ = 0;
        private Object messageResponse_;
        public MessageResponseCase
        getMessageResponseCase() {
            return MessageResponseCase.forNumber(
                messageResponseCase_);
        }

        public Builder clearMessageResponse() {
            messageResponseCase_ = 0;
            messageResponse_ = null;
            onChanged();
            return this;
        }

        private int bitField0_;

        private Object validHost_ = "";
        /**
         * <code>string valid_host = 1;</code>
         * @return The validHost.
         */
        public String getValidHost() {
            Object ref = validHost_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                validHost_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }
        /**
         * <code>string valid_host = 1;</code>
         * @return The bytes for validHost.
         */
        public com.google.protobuf.ByteString
        getValidHostBytes() {
            Object ref = validHost_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
                validHost_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string valid_host = 1;</code>
         * @param value The validHost to set.
         * @return This builder for chaining.
         */
        public Builder setValidHost(
            String value) {
            if (value == null) { throw new NullPointerException(); }
            validHost_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        /**
         * <code>string valid_host = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearValidHost() {
            validHost_ = getDefaultInstance().getValidHost();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }
        /**
         * <code>string valid_host = 1;</code>
         * @param value The bytes for validHost to set.
         * @return This builder for chaining.
         */
        public Builder setValidHostBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) { throw new NullPointerException(); }
            checkByteStringIsUtf8(value);
            validHost_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        private io.grpc.reflection.v1alpha.ServerReflectionRequest originalRequest_;
        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.ServerReflectionRequest, io.grpc.reflection.v1alpha.ServerReflectionRequest.Builder, io.grpc.reflection.v1alpha.ServerReflectionRequestOrBuilder> originalRequestBuilder_;
        /**
         * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
         * @return Whether the originalRequest field is set.
         */
        public boolean hasOriginalRequest() {
            return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
         * @return The originalRequest.
         */
        public io.grpc.reflection.v1alpha.ServerReflectionRequest getOriginalRequest() {
            if (originalRequestBuilder_ == null) {
                return originalRequest_ == null ? io.grpc.reflection.v1alpha.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
            } else {
                return originalRequestBuilder_.getMessage();
            }
        }
        /**
         * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
         */
        public Builder setOriginalRequest(io.grpc.reflection.v1alpha.ServerReflectionRequest value) {
            if (originalRequestBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                originalRequest_ = value;
            } else {
                originalRequestBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
         */
        public Builder setOriginalRequest(
            io.grpc.reflection.v1alpha.ServerReflectionRequest.Builder builderForValue) {
            if (originalRequestBuilder_ == null) {
                originalRequest_ = builderForValue.build();
            } else {
                originalRequestBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
         */
        public Builder mergeOriginalRequest(io.grpc.reflection.v1alpha.ServerReflectionRequest value) {
            if (originalRequestBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0) &&
                    originalRequest_ != null &&
                    originalRequest_ != io.grpc.reflection.v1alpha.ServerReflectionRequest.getDefaultInstance()) {
                    getOriginalRequestBuilder().mergeFrom(value);
                } else {
                    originalRequest_ = value;
                }
            } else {
                originalRequestBuilder_.mergeFrom(value);
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
         */
        public Builder clearOriginalRequest() {
            bitField0_ = (bitField0_ & ~0x00000002);
            originalRequest_ = null;
            if (originalRequestBuilder_ != null) {
                originalRequestBuilder_.dispose();
                originalRequestBuilder_ = null;
            }
            onChanged();
            return this;
        }
        /**
         * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
         */
        public io.grpc.reflection.v1alpha.ServerReflectionRequest.Builder getOriginalRequestBuilder() {
            bitField0_ |= 0x00000002;
            onChanged();
            return getOriginalRequestFieldBuilder().getBuilder();
        }
        /**
         * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
         */
        public io.grpc.reflection.v1alpha.ServerReflectionRequestOrBuilder getOriginalRequestOrBuilder() {
            if (originalRequestBuilder_ != null) {
                return originalRequestBuilder_.getMessageOrBuilder();
            } else {
                return originalRequest_ == null ?
                    io.grpc.reflection.v1alpha.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
            }
        }
        /**
         * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.ServerReflectionRequest, io.grpc.reflection.v1alpha.ServerReflectionRequest.Builder, io.grpc.reflection.v1alpha.ServerReflectionRequestOrBuilder>
        getOriginalRequestFieldBuilder() {
            if (originalRequestBuilder_ == null) {
                originalRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                    io.grpc.reflection.v1alpha.ServerReflectionRequest, io.grpc.reflection.v1alpha.ServerReflectionRequest.Builder, io.grpc.reflection.v1alpha.ServerReflectionRequestOrBuilder>(
                    getOriginalRequest(),
                    getParentForChildren(),
                    isClean());
                originalRequest_ = null;
            }
            return originalRequestBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.FileDescriptorResponse, io.grpc.reflection.v1alpha.FileDescriptorResponse.Builder, io.grpc.reflection.v1alpha.FileDescriptorResponseOrBuilder> fileDescriptorResponseBuilder_;
        /**
         * <pre>
         * This message is used to answer file_by_filename, file_containing_symbol,
         * file_containing_extension requests with transitive dependencies. As
         * the repeated label is not allowed in oneof fields, we use a
         * FileDescriptorResponse message to encapsulate the repeated fields.
         * The reflection service is allowed to avoid sending FileDescriptorProtos
         * that were previously sent in response to earlier requests in the stream.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
         * @return Whether the fileDescriptorResponse field is set.
         */
        @Override
        public boolean hasFileDescriptorResponse() {
            return messageResponseCase_ == 4;
        }
        /**
         * <pre>
         * This message is used to answer file_by_filename, file_containing_symbol,
         * file_containing_extension requests with transitive dependencies. As
         * the repeated label is not allowed in oneof fields, we use a
         * FileDescriptorResponse message to encapsulate the repeated fields.
         * The reflection service is allowed to avoid sending FileDescriptorProtos
         * that were previously sent in response to earlier requests in the stream.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
         * @return The fileDescriptorResponse.
         */
        @Override
        public io.grpc.reflection.v1alpha.FileDescriptorResponse getFileDescriptorResponse() {
            if (fileDescriptorResponseBuilder_ == null) {
                if (messageResponseCase_ == 4) {
                    return (io.grpc.reflection.v1alpha.FileDescriptorResponse) messageResponse_;
                }
                return io.grpc.reflection.v1alpha.FileDescriptorResponse.getDefaultInstance();
            } else {
                if (messageResponseCase_ == 4) {
                    return fileDescriptorResponseBuilder_.getMessage();
                }
                return io.grpc.reflection.v1alpha.FileDescriptorResponse.getDefaultInstance();
            }
        }
        /**
         * <pre>
         * This message is used to answer file_by_filename, file_containing_symbol,
         * file_containing_extension requests with transitive dependencies. As
         * the repeated label is not allowed in oneof fields, we use a
         * FileDescriptorResponse message to encapsulate the repeated fields.
         * The reflection service is allowed to avoid sending FileDescriptorProtos
         * that were previously sent in response to earlier requests in the stream.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
         */
        public Builder setFileDescriptorResponse(io.grpc.reflection.v1alpha.FileDescriptorResponse value) {
            if (fileDescriptorResponseBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                messageResponse_ = value;
                onChanged();
            } else {
                fileDescriptorResponseBuilder_.setMessage(value);
            }
            messageResponseCase_ = 4;
            return this;
        }
        /**
         * <pre>
         * This message is used to answer file_by_filename, file_containing_symbol,
         * file_containing_extension requests with transitive dependencies. As
         * the repeated label is not allowed in oneof fields, we use a
         * FileDescriptorResponse message to encapsulate the repeated fields.
         * The reflection service is allowed to avoid sending FileDescriptorProtos
         * that were previously sent in response to earlier requests in the stream.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
         */
        public Builder setFileDescriptorResponse(
            io.grpc.reflection.v1alpha.FileDescriptorResponse.Builder builderForValue) {
            if (fileDescriptorResponseBuilder_ == null) {
                messageResponse_ = builderForValue.build();
                onChanged();
            } else {
                fileDescriptorResponseBuilder_.setMessage(builderForValue.build());
            }
            messageResponseCase_ = 4;
            return this;
        }
        /**
         * <pre>
         * This message is used to answer file_by_filename, file_containing_symbol,
         * file_containing_extension requests with transitive dependencies. As
         * the repeated label is not allowed in oneof fields, we use a
         * FileDescriptorResponse message to encapsulate the repeated fields.
         * The reflection service is allowed to avoid sending FileDescriptorProtos
         * that were previously sent in response to earlier requests in the stream.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
         */
        public Builder mergeFileDescriptorResponse(io.grpc.reflection.v1alpha.FileDescriptorResponse value) {
            if (fileDescriptorResponseBuilder_ == null) {
                if (messageResponseCase_ == 4 &&
                    messageResponse_ != io.grpc.reflection.v1alpha.FileDescriptorResponse.getDefaultInstance()) {
                    messageResponse_ = io.grpc.reflection.v1alpha.FileDescriptorResponse.newBuilder((io.grpc.reflection.v1alpha.FileDescriptorResponse) messageResponse_)
                        .mergeFrom(value).buildPartial();
                } else {
                    messageResponse_ = value;
                }
                onChanged();
            } else {
                if (messageResponseCase_ == 4) {
                    fileDescriptorResponseBuilder_.mergeFrom(value);
                } else {
                    fileDescriptorResponseBuilder_.setMessage(value);
                }
            }
            messageResponseCase_ = 4;
            return this;
        }
        /**
         * <pre>
         * This message is used to answer file_by_filename, file_containing_symbol,
         * file_containing_extension requests with transitive dependencies. As
         * the repeated label is not allowed in oneof fields, we use a
         * FileDescriptorResponse message to encapsulate the repeated fields.
         * The reflection service is allowed to avoid sending FileDescriptorProtos
         * that were previously sent in response to earlier requests in the stream.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
         */
        public Builder clearFileDescriptorResponse() {
            if (fileDescriptorResponseBuilder_ == null) {
                if (messageResponseCase_ == 4) {
                    messageResponseCase_ = 0;
                    messageResponse_ = null;
                    onChanged();
                }
            } else {
                if (messageResponseCase_ == 4) {
                    messageResponseCase_ = 0;
                    messageResponse_ = null;
                }
                fileDescriptorResponseBuilder_.clear();
            }
            return this;
        }
        /**
         * <pre>
         * This message is used to answer file_by_filename, file_containing_symbol,
         * file_containing_extension requests with transitive dependencies. As
         * the repeated label is not allowed in oneof fields, we use a
         * FileDescriptorResponse message to encapsulate the repeated fields.
         * The reflection service is allowed to avoid sending FileDescriptorProtos
         * that were previously sent in response to earlier requests in the stream.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
         */
        public io.grpc.reflection.v1alpha.FileDescriptorResponse.Builder getFileDescriptorResponseBuilder() {
            return getFileDescriptorResponseFieldBuilder().getBuilder();
        }
        /**
         * <pre>
         * This message is used to answer file_by_filename, file_containing_symbol,
         * file_containing_extension requests with transitive dependencies. As
         * the repeated label is not allowed in oneof fields, we use a
         * FileDescriptorResponse message to encapsulate the repeated fields.
         * The reflection service is allowed to avoid sending FileDescriptorProtos
         * that were previously sent in response to earlier requests in the stream.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
         */
        @Override
        public io.grpc.reflection.v1alpha.FileDescriptorResponseOrBuilder getFileDescriptorResponseOrBuilder() {
            if ((messageResponseCase_ == 4) && (fileDescriptorResponseBuilder_ != null)) {
                return fileDescriptorResponseBuilder_.getMessageOrBuilder();
            } else {
                if (messageResponseCase_ == 4) {
                    return (io.grpc.reflection.v1alpha.FileDescriptorResponse) messageResponse_;
                }
                return io.grpc.reflection.v1alpha.FileDescriptorResponse.getDefaultInstance();
            }
        }
        /**
         * <pre>
         * This message is used to answer file_by_filename, file_containing_symbol,
         * file_containing_extension requests with transitive dependencies. As
         * the repeated label is not allowed in oneof fields, we use a
         * FileDescriptorResponse message to encapsulate the repeated fields.
         * The reflection service is allowed to avoid sending FileDescriptorProtos
         * that were previously sent in response to earlier requests in the stream.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.FileDescriptorResponse, io.grpc.reflection.v1alpha.FileDescriptorResponse.Builder, io.grpc.reflection.v1alpha.FileDescriptorResponseOrBuilder>
        getFileDescriptorResponseFieldBuilder() {
            if (fileDescriptorResponseBuilder_ == null) {
                if (!(messageResponseCase_ == 4)) {
                    messageResponse_ = io.grpc.reflection.v1alpha.FileDescriptorResponse.getDefaultInstance();
                }
                fileDescriptorResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                    io.grpc.reflection.v1alpha.FileDescriptorResponse, io.grpc.reflection.v1alpha.FileDescriptorResponse.Builder, io.grpc.reflection.v1alpha.FileDescriptorResponseOrBuilder>(
                    (io.grpc.reflection.v1alpha.FileDescriptorResponse) messageResponse_,
                    getParentForChildren(),
                    isClean());
                messageResponse_ = null;
            }
            messageResponseCase_ = 4;
            onChanged();
            return fileDescriptorResponseBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.ExtensionNumberResponse, io.grpc.reflection.v1alpha.ExtensionNumberResponse.Builder, io.grpc.reflection.v1alpha.ExtensionNumberResponseOrBuilder> allExtensionNumbersResponseBuilder_;
        /**
         * <pre>
         * This message is used to answer all_extension_numbers_of_type requst.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
         * @return Whether the allExtensionNumbersResponse field is set.
         */
        @Override
        public boolean hasAllExtensionNumbersResponse() {
            return messageResponseCase_ == 5;
        }
        /**
         * <pre>
         * This message is used to answer all_extension_numbers_of_type requst.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
         * @return The allExtensionNumbersResponse.
         */
        @Override
        public io.grpc.reflection.v1alpha.ExtensionNumberResponse getAllExtensionNumbersResponse() {
            if (allExtensionNumbersResponseBuilder_ == null) {
                if (messageResponseCase_ == 5) {
                    return (io.grpc.reflection.v1alpha.ExtensionNumberResponse) messageResponse_;
                }
                return io.grpc.reflection.v1alpha.ExtensionNumberResponse.getDefaultInstance();
            } else {
                if (messageResponseCase_ == 5) {
                    return allExtensionNumbersResponseBuilder_.getMessage();
                }
                return io.grpc.reflection.v1alpha.ExtensionNumberResponse.getDefaultInstance();
            }
        }
        /**
         * <pre>
         * This message is used to answer all_extension_numbers_of_type requst.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
         */
        public Builder setAllExtensionNumbersResponse(io.grpc.reflection.v1alpha.ExtensionNumberResponse value) {
            if (allExtensionNumbersResponseBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                messageResponse_ = value;
                onChanged();
            } else {
                allExtensionNumbersResponseBuilder_.setMessage(value);
            }
            messageResponseCase_ = 5;
            return this;
        }
        /**
         * <pre>
         * This message is used to answer all_extension_numbers_of_type requst.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
         */
        public Builder setAllExtensionNumbersResponse(
            io.grpc.reflection.v1alpha.ExtensionNumberResponse.Builder builderForValue) {
            if (allExtensionNumbersResponseBuilder_ == null) {
                messageResponse_ = builderForValue.build();
                onChanged();
            } else {
                allExtensionNumbersResponseBuilder_.setMessage(builderForValue.build());
            }
            messageResponseCase_ = 5;
            return this;
        }
        /**
         * <pre>
         * This message is used to answer all_extension_numbers_of_type requst.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
         */
        public Builder mergeAllExtensionNumbersResponse(io.grpc.reflection.v1alpha.ExtensionNumberResponse value) {
            if (allExtensionNumbersResponseBuilder_ == null) {
                if (messageResponseCase_ == 5 &&
                    messageResponse_ != io.grpc.reflection.v1alpha.ExtensionNumberResponse.getDefaultInstance()) {
                    messageResponse_ = io.grpc.reflection.v1alpha.ExtensionNumberResponse.newBuilder((io.grpc.reflection.v1alpha.ExtensionNumberResponse) messageResponse_)
                        .mergeFrom(value).buildPartial();
                } else {
                    messageResponse_ = value;
                }
                onChanged();
            } else {
                if (messageResponseCase_ == 5) {
                    allExtensionNumbersResponseBuilder_.mergeFrom(value);
                } else {
                    allExtensionNumbersResponseBuilder_.setMessage(value);
                }
            }
            messageResponseCase_ = 5;
            return this;
        }
        /**
         * <pre>
         * This message is used to answer all_extension_numbers_of_type requst.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
         */
        public Builder clearAllExtensionNumbersResponse() {
            if (allExtensionNumbersResponseBuilder_ == null) {
                if (messageResponseCase_ == 5) {
                    messageResponseCase_ = 0;
                    messageResponse_ = null;
                    onChanged();
                }
            } else {
                if (messageResponseCase_ == 5) {
                    messageResponseCase_ = 0;
                    messageResponse_ = null;
                }
                allExtensionNumbersResponseBuilder_.clear();
            }
            return this;
        }
        /**
         * <pre>
         * This message is used to answer all_extension_numbers_of_type requst.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
         */
        public io.grpc.reflection.v1alpha.ExtensionNumberResponse.Builder getAllExtensionNumbersResponseBuilder() {
            return getAllExtensionNumbersResponseFieldBuilder().getBuilder();
        }
        /**
         * <pre>
         * This message is used to answer all_extension_numbers_of_type requst.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
         */
        @Override
        public io.grpc.reflection.v1alpha.ExtensionNumberResponseOrBuilder getAllExtensionNumbersResponseOrBuilder() {
            if ((messageResponseCase_ == 5) && (allExtensionNumbersResponseBuilder_ != null)) {
                return allExtensionNumbersResponseBuilder_.getMessageOrBuilder();
            } else {
                if (messageResponseCase_ == 5) {
                    return (io.grpc.reflection.v1alpha.ExtensionNumberResponse) messageResponse_;
                }
                return io.grpc.reflection.v1alpha.ExtensionNumberResponse.getDefaultInstance();
            }
        }
        /**
         * <pre>
         * This message is used to answer all_extension_numbers_of_type requst.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.ExtensionNumberResponse, io.grpc.reflection.v1alpha.ExtensionNumberResponse.Builder, io.grpc.reflection.v1alpha.ExtensionNumberResponseOrBuilder>
        getAllExtensionNumbersResponseFieldBuilder() {
            if (allExtensionNumbersResponseBuilder_ == null) {
                if (!(messageResponseCase_ == 5)) {
                    messageResponse_ = io.grpc.reflection.v1alpha.ExtensionNumberResponse.getDefaultInstance();
                }
                allExtensionNumbersResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                    io.grpc.reflection.v1alpha.ExtensionNumberResponse, io.grpc.reflection.v1alpha.ExtensionNumberResponse.Builder, io.grpc.reflection.v1alpha.ExtensionNumberResponseOrBuilder>(
                    (io.grpc.reflection.v1alpha.ExtensionNumberResponse) messageResponse_,
                    getParentForChildren(),
                    isClean());
                messageResponse_ = null;
            }
            messageResponseCase_ = 5;
            onChanged();
            return allExtensionNumbersResponseBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.ListServiceResponse, io.grpc.reflection.v1alpha.ListServiceResponse.Builder, io.grpc.reflection.v1alpha.ListServiceResponseOrBuilder> listServicesResponseBuilder_;
        /**
         * <pre>
         * This message is used to answer list_services request.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
         * @return Whether the listServicesResponse field is set.
         */
        @Override
        public boolean hasListServicesResponse() {
            return messageResponseCase_ == 6;
        }
        /**
         * <pre>
         * This message is used to answer list_services request.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
         * @return The listServicesResponse.
         */
        @Override
        public io.grpc.reflection.v1alpha.ListServiceResponse getListServicesResponse() {
            if (listServicesResponseBuilder_ == null) {
                if (messageResponseCase_ == 6) {
                    return (io.grpc.reflection.v1alpha.ListServiceResponse) messageResponse_;
                }
                return io.grpc.reflection.v1alpha.ListServiceResponse.getDefaultInstance();
            } else {
                if (messageResponseCase_ == 6) {
                    return listServicesResponseBuilder_.getMessage();
                }
                return io.grpc.reflection.v1alpha.ListServiceResponse.getDefaultInstance();
            }
        }
        /**
         * <pre>
         * This message is used to answer list_services request.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
         */
        public Builder setListServicesResponse(io.grpc.reflection.v1alpha.ListServiceResponse value) {
            if (listServicesResponseBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                messageResponse_ = value;
                onChanged();
            } else {
                listServicesResponseBuilder_.setMessage(value);
            }
            messageResponseCase_ = 6;
            return this;
        }
        /**
         * <pre>
         * This message is used to answer list_services request.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
         */
        public Builder setListServicesResponse(
            io.grpc.reflection.v1alpha.ListServiceResponse.Builder builderForValue) {
            if (listServicesResponseBuilder_ == null) {
                messageResponse_ = builderForValue.build();
                onChanged();
            } else {
                listServicesResponseBuilder_.setMessage(builderForValue.build());
            }
            messageResponseCase_ = 6;
            return this;
        }
        /**
         * <pre>
         * This message is used to answer list_services request.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
         */
        public Builder mergeListServicesResponse(io.grpc.reflection.v1alpha.ListServiceResponse value) {
            if (listServicesResponseBuilder_ == null) {
                if (messageResponseCase_ == 6 &&
                    messageResponse_ != io.grpc.reflection.v1alpha.ListServiceResponse.getDefaultInstance()) {
                    messageResponse_ = io.grpc.reflection.v1alpha.ListServiceResponse.newBuilder((io.grpc.reflection.v1alpha.ListServiceResponse) messageResponse_)
                        .mergeFrom(value).buildPartial();
                } else {
                    messageResponse_ = value;
                }
                onChanged();
            } else {
                if (messageResponseCase_ == 6) {
                    listServicesResponseBuilder_.mergeFrom(value);
                } else {
                    listServicesResponseBuilder_.setMessage(value);
                }
            }
            messageResponseCase_ = 6;
            return this;
        }
        /**
         * <pre>
         * This message is used to answer list_services request.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
         */
        public Builder clearListServicesResponse() {
            if (listServicesResponseBuilder_ == null) {
                if (messageResponseCase_ == 6) {
                    messageResponseCase_ = 0;
                    messageResponse_ = null;
                    onChanged();
                }
            } else {
                if (messageResponseCase_ == 6) {
                    messageResponseCase_ = 0;
                    messageResponse_ = null;
                }
                listServicesResponseBuilder_.clear();
            }
            return this;
        }
        /**
         * <pre>
         * This message is used to answer list_services request.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
         */
        public io.grpc.reflection.v1alpha.ListServiceResponse.Builder getListServicesResponseBuilder() {
            return getListServicesResponseFieldBuilder().getBuilder();
        }
        /**
         * <pre>
         * This message is used to answer list_services request.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
         */
        @Override
        public io.grpc.reflection.v1alpha.ListServiceResponseOrBuilder getListServicesResponseOrBuilder() {
            if ((messageResponseCase_ == 6) && (listServicesResponseBuilder_ != null)) {
                return listServicesResponseBuilder_.getMessageOrBuilder();
            } else {
                if (messageResponseCase_ == 6) {
                    return (io.grpc.reflection.v1alpha.ListServiceResponse) messageResponse_;
                }
                return io.grpc.reflection.v1alpha.ListServiceResponse.getDefaultInstance();
            }
        }
        /**
         * <pre>
         * This message is used to answer list_services request.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.ListServiceResponse, io.grpc.reflection.v1alpha.ListServiceResponse.Builder, io.grpc.reflection.v1alpha.ListServiceResponseOrBuilder>
        getListServicesResponseFieldBuilder() {
            if (listServicesResponseBuilder_ == null) {
                if (!(messageResponseCase_ == 6)) {
                    messageResponse_ = io.grpc.reflection.v1alpha.ListServiceResponse.getDefaultInstance();
                }
                listServicesResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                    io.grpc.reflection.v1alpha.ListServiceResponse, io.grpc.reflection.v1alpha.ListServiceResponse.Builder, io.grpc.reflection.v1alpha.ListServiceResponseOrBuilder>(
                    (io.grpc.reflection.v1alpha.ListServiceResponse) messageResponse_,
                    getParentForChildren(),
                    isClean());
                messageResponse_ = null;
            }
            messageResponseCase_ = 6;
            onChanged();
            return listServicesResponseBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.ErrorResponse, io.grpc.reflection.v1alpha.ErrorResponse.Builder, io.grpc.reflection.v1alpha.ErrorResponseOrBuilder> errorResponseBuilder_;
        /**
         * <pre>
         * This message is used when an error occurs.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
         * @return Whether the errorResponse field is set.
         */
        @Override
        public boolean hasErrorResponse() {
            return messageResponseCase_ == 7;
        }
        /**
         * <pre>
         * This message is used when an error occurs.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
         * @return The errorResponse.
         */
        @Override
        public io.grpc.reflection.v1alpha.ErrorResponse getErrorResponse() {
            if (errorResponseBuilder_ == null) {
                if (messageResponseCase_ == 7) {
                    return (io.grpc.reflection.v1alpha.ErrorResponse) messageResponse_;
                }
                return io.grpc.reflection.v1alpha.ErrorResponse.getDefaultInstance();
            } else {
                if (messageResponseCase_ == 7) {
                    return errorResponseBuilder_.getMessage();
                }
                return io.grpc.reflection.v1alpha.ErrorResponse.getDefaultInstance();
            }
        }
        /**
         * <pre>
         * This message is used when an error occurs.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
         */
        public Builder setErrorResponse(io.grpc.reflection.v1alpha.ErrorResponse value) {
            if (errorResponseBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                messageResponse_ = value;
                onChanged();
            } else {
                errorResponseBuilder_.setMessage(value);
            }
            messageResponseCase_ = 7;
            return this;
        }
        /**
         * <pre>
         * This message is used when an error occurs.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
         */
        public Builder setErrorResponse(
            io.grpc.reflection.v1alpha.ErrorResponse.Builder builderForValue) {
            if (errorResponseBuilder_ == null) {
                messageResponse_ = builderForValue.build();
                onChanged();
            } else {
                errorResponseBuilder_.setMessage(builderForValue.build());
            }
            messageResponseCase_ = 7;
            return this;
        }
        /**
         * <pre>
         * This message is used when an error occurs.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
         */
        public Builder mergeErrorResponse(io.grpc.reflection.v1alpha.ErrorResponse value) {
            if (errorResponseBuilder_ == null) {
                if (messageResponseCase_ == 7 &&
                    messageResponse_ != io.grpc.reflection.v1alpha.ErrorResponse.getDefaultInstance()) {
                    messageResponse_ = io.grpc.reflection.v1alpha.ErrorResponse.newBuilder((io.grpc.reflection.v1alpha.ErrorResponse) messageResponse_)
                        .mergeFrom(value).buildPartial();
                } else {
                    messageResponse_ = value;
                }
                onChanged();
            } else {
                if (messageResponseCase_ == 7) {
                    errorResponseBuilder_.mergeFrom(value);
                } else {
                    errorResponseBuilder_.setMessage(value);
                }
            }
            messageResponseCase_ = 7;
            return this;
        }
        /**
         * <pre>
         * This message is used when an error occurs.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
         */
        public Builder clearErrorResponse() {
            if (errorResponseBuilder_ == null) {
                if (messageResponseCase_ == 7) {
                    messageResponseCase_ = 0;
                    messageResponse_ = null;
                    onChanged();
                }
            } else {
                if (messageResponseCase_ == 7) {
                    messageResponseCase_ = 0;
                    messageResponse_ = null;
                }
                errorResponseBuilder_.clear();
            }
            return this;
        }
        /**
         * <pre>
         * This message is used when an error occurs.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
         */
        public io.grpc.reflection.v1alpha.ErrorResponse.Builder getErrorResponseBuilder() {
            return getErrorResponseFieldBuilder().getBuilder();
        }
        /**
         * <pre>
         * This message is used when an error occurs.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
         */
        @Override
        public io.grpc.reflection.v1alpha.ErrorResponseOrBuilder getErrorResponseOrBuilder() {
            if ((messageResponseCase_ == 7) && (errorResponseBuilder_ != null)) {
                return errorResponseBuilder_.getMessageOrBuilder();
            } else {
                if (messageResponseCase_ == 7) {
                    return (io.grpc.reflection.v1alpha.ErrorResponse) messageResponse_;
                }
                return io.grpc.reflection.v1alpha.ErrorResponse.getDefaultInstance();
            }
        }
        /**
         * <pre>
         * This message is used when an error occurs.
         * </pre>
         *
         * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.reflection.v1alpha.ErrorResponse, io.grpc.reflection.v1alpha.ErrorResponse.Builder, io.grpc.reflection.v1alpha.ErrorResponseOrBuilder>
        getErrorResponseFieldBuilder() {
            if (errorResponseBuilder_ == null) {
                if (!(messageResponseCase_ == 7)) {
                    messageResponse_ = io.grpc.reflection.v1alpha.ErrorResponse.getDefaultInstance();
                }
                errorResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                    io.grpc.reflection.v1alpha.ErrorResponse, io.grpc.reflection.v1alpha.ErrorResponse.Builder, io.grpc.reflection.v1alpha.ErrorResponseOrBuilder>(
                    (io.grpc.reflection.v1alpha.ErrorResponse) messageResponse_,
                    getParentForChildren(),
                    isClean());
                messageResponse_ = null;
            }
            messageResponseCase_ = 7;
            onChanged();
            return errorResponseBuilder_;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.ServerReflectionResponse)
    }

    // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.ServerReflectionResponse)
    private static final io.grpc.reflection.v1alpha.ServerReflectionResponse DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new io.grpc.reflection.v1alpha.ServerReflectionResponse();
    }

    public static io.grpc.reflection.v1alpha.ServerReflectionResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerReflectionResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServerReflectionResponse>() {
        @Override
        public ServerReflectionResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                    .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ServerReflectionResponse> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServerReflectionResponse> getParserForType() {
        return PARSER;
    }

    @Override
    public io.grpc.reflection.v1alpha.ServerReflectionResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

